#! /usr/bin/env python

from os import chdir
from sys import argv
from glob import glob

chdir(argv[1])

f = open("messages.html", "wt")
f.write('<html>\n<div style="max-width: 650px; margin-left:auto; margin-right:auto; ">')
f.write("""
    <style TYPE="text/css">
       <!--
       hr { display: none; }
       h1 { -webkit-margin-before: 1opx;
            -webkit-margin-after: 10px; }
       ul { -webkit-margin-before: 10px;
            -webkit-margin-after: 10px;
            -webkit-padding-start: 0px;
            list-style-type: none; }
       --!>
    </style>
""")

msg_files = glob("msg*.html")
msg_files.sort()
sep = ""
for msg in msg_files:
    f.write(sep)
    # print msg
    lines = open(msg, "rt").readlines()
    while lines:
        if "X-MsgBody" in lines[0]:
            break
        lines.pop(0)
    lines.pop(0)
    while lines:
        if "X-Body-of-Message-End" in lines[0]:
            break
        f.write(lines.pop(0)) #.replace("<h1>", "<h1 tabindex=0>"))
    sep = '<br><hr size="3" color="black" style="display: block;" />\n'
f.write('</div>\n</html>\n')
f.close()
